version: '3.7'

x-blob_dir: &blob_dir
  environment:
    BLOB_DIR: '/colinfs'
  volumes:
    - shared_data:/colinfs

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'colin'
    ports:
      - 5432:5432
  server:
    image: colinthecomputer
    build: .
    <<: *blob_dir
    depends_on:
      - rabbitmq
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.server run-server 'rabbitmq://rabbitmq:5672'
  pose_parser:
    image: colinthecomputer
    <<: *blob_dir
    depends_on: 
      - server
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.parsers run-parser 'pose' 'rabbitmq://rabbitmq:5672'
  color_image_parser:
    image: colinthecomputer
    <<: *blob_dir
    depends_on: 
      - server
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.parsers run-parser 'color_image' 'rabbitmq://rabbitmq:5672'
  depth_image_parser:
    image: colinthecomputer
    <<: *blob_dir
    depends_on: 
      - server
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.parsers run-parser 'depth_image' 'rabbitmq://rabbitmq:5672'
  feelings_parser:
    image: colinthecomputer
    <<: *blob_dir
    depends_on: 
      - server
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.parsers run-parser 'feelings' 'rabbitmq://rabbitmq:5672'
  saver:
    image: colinthecomputer
    <<: *blob_dir
    depends_on:
      - server
      - rabbitmq
      - postgres
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.saver run-saver 'postgresql://colin:password@postgres:5432/colin' 'rabbitmq://rabbitmq:5672/'
  api:
    image: colinthecomputer
    <<: *blob_dir
    depends_on:
      - server
      - postgres
    ports:
      - 5000:5000
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.api run-server -d 'postgresql://colin:password@postgres:5432/colin'
  gui:
    image: colinthecomputer
    <<: *blob_dir
    depends_on:
      - server
      - postgres
    ports:
      - 8080:8080
    command: ./wait-for-it.sh rabbitmq:5672 -- python3.8 -m colinthecomputer.gui run-server
  

volumes:
  shared_data: